export enum REGISTER_TYPE {
  FARMER = "farmer",
  // WORKER = "worker",
  PURCHASER = "purchaser",
  // TRADER = "trader",
  // INSPECTOR = "inspector",
  COMPANY = "company",
  ADMIN = "admin",
  TRANSPORTER = "transport",
  FACTORY = "factory",
  BUSINESS = "sales",
}

export const REGISTER_TYPE_LABEL: Record<REGISTER_TYPE, string> = {
  [REGISTER_TYPE.FARMER]: "Nông hộ",
  // [REGISTER_TYPE.WORKER]: "Tá điền",
  [REGISTER_TYPE.PURCHASER]: "Thu mua",
  // [REGISTER_TYPE.TRADER]: "Thương lái",
  // [REGISTER_TYPE.INSPECTOR]: "Kiểm soát viên",
  [REGISTER_TYPE.COMPANY]: "Công ty",
  [REGISTER_TYPE.ADMIN]: "Quản trị viên",
  [REGISTER_TYPE.TRANSPORTER]: "Vận chuyển",
  [REGISTER_TYPE.FACTORY]: "Nhà máy",
  [REGISTER_TYPE.BUSINESS]: "Bán hàng",
};

export const functionalities: Record<REGISTER_TYPE, string[]> = {
  [REGISTER_TYPE.FARMER]: [
    "Đăng ký tài khoản (mặc định)",
    "Kết nối/ ngừng kết nối Khảo sát viên",
    "Kết nối/ ngừng kết nối Thu Mua",
    "Kết nối/ ngừng kết nối Công ty",
    "Ủy quyền cho Khảo sát viên",
    "Kết nối/ ngừng kết nối với Farmer",
    "Chia sẻ vườn với Farmer",
    "Khai báo thông tin Land",
    "Khai báo thông tin Plant",
    "Tạo lịch thu hoạch",
    "Xem danh sách Phiếu Bán",
  ],
  [REGISTER_TYPE.PURCHASER]: [
    "Đăng ký tài khoản (mặc định)",
    "Kết nối/ ngừng kết nối Farmer",
    "Kết nối/ ngừng kết nối Thu Mua",
    "Kết nối/ ngừng kết nối Công ty",
    "Tạo Phiếu Bán (cho Thu Mua/ Công ty)",
    "Tạo phiếu Mua (với Farmer/ Thu Mua)",
    "Khai báo thông tin Land",
    "Khai báo thông tin Plant",
    "Xác nhận sản lượng lịch thu hoạch",
  ],
  // [REGISTER_TYPE.TRADER]: [
  //   "Đăng ký tài khoản (mặc định)",
  //   "Kết nối/ ngừng kết nối Farmer",
  //   "Kết nối/ ngừng kết nối Thu Mua",
  //   "Kết nối/ ngừng kết nối Công ty",
  //   "Tạo Phiếu Bán (cho Nhà Máy)",
  //   "Tạo phiếu Mua (với Farmer / Thu Mua)",
  //   "Có danh sách được chia sẻ từ Nông hộ",
  //   "Xác nhận sản lượng lịch thu hoạch",
  // ],
  // [REGISTER_TYPE.INSPECTOR]: [
  //   "Đăng ký tài khoản (mặc định)",
  //   "Kết nối/ ngừng kết nối Farmer",
  //   "Ủy quyền từ Nông hộ",
  //   "Kiểm tra thông tin Land",
  //   "Kiểm tra thông tin Plant",
  // ],
  [REGISTER_TYPE.COMPANY]: [
    "Đăng ký tài khoản (mặc định)",
    "Kết nối/ ngừng kết nối Farmer",
    "Kết nối/ ngừng kết nối Thương Lái",
    "Kết nối/ ngừng kết nối Thu Mua",
    "Lịch sản xuất",
    "Xuất dữ liệu JSON",
  ],
  [REGISTER_TYPE.TRANSPORTER]: [
    "Đăng ký tài khoản (mặc định)",
    "Quản lý phương tiện",
    "Nhận đơn vận chuyển",
    "Theo dõi lộ trình",
  ],
  [REGISTER_TYPE.FACTORY]: [
    "Đăng ký tài khoản (mặc định)",
    "Quản lý kho",
    "Quy trình chế biến",
    "Đóng gói sản phẩm",
  ],
  [REGISTER_TYPE.BUSINESS]: [
    "Đăng ký tài khoản (mặc định)",
    "Quản lý đơn hàng",
    "Thống kê doanh thu",
    "Báo cáo thị trường",
  ],
  // [REGISTER_TYPE.WORKER]: [],
  [REGISTER_TYPE.ADMIN]: [],
};
